### ISSUE TITLE
Enhancement: Remove ROOT as a dependency.

### ISSUE THREAD

**Issue by KonstantinSchubert** [scikit-hep/root_pandas#23]
Seriously :)

This should be a long-term goal because it would:
... make installing root_pandas so much easier.
... mean that a lot of users will not need to install ROOT at all.

I am aware that this is ambitious.

Since we depend on ROOT via root_numpy, the simlest way to go would be to remove the ROOT dependency in root_numpy. Alternatively, one could define a stripped-down version of root_numpy which contains only the parts that we actually depend on and then try to remove its dependency. 

It is true, I have no idea how much work that is....

https://root.cern.ch/root/InputOutput.html

**Comment by MaxNoe** [comment]
Do I get it right? You mean to reimplement writing and reading root files in python / a python c extension?

**Comment by KonstantinSchubert** [comment]
I don't know, I mainly wanted to start a discussion about it.

I certainly don't expect this issue to remain open until it is fixed.

Maximilian Nöthe <notifications@github.com> schrieb am Di., 10. Mai 2016
17:19:

**Comment by remenska** [comment]
+1

**Comment by ibab** [comment]
I'm definitely 👍 on this, but after trying to create a minimal (only IO) version of ROOT myself, I have to say that it looks like an extremely difficult task.
There are extreme interdependencies between each of the components of ROOT, and it seems extremely difficult to extract any part of it.
For example, I couldn't see a way of retaining the TTree part of the source code without also keeping the custom LLVM version that ROOT includes in its source tree.
We could also open an issue on this in the `root_numpy` repository.

**Comment by eduardo-rodrigues** [comment]
Hi all,
As pointed out in issue https://github.com/scikit-hep/root_pandas/issues/44, this idea is not a reality to a very large extent, see the uproot package in this org - https://github.com/scikit-hep/uproot.
I would suggest that we hence close this issue and continue the discussion in issue #44.
@ibab, @chrisburr, @alexpearce, do close if you agree :-).
Thanks.

**Comment by chrisburr** [comment]
Agreed 👍
