### ISSUE TITLE
Implement ROOTStore

### ISSUE THREAD

**Issue by ibab** [scikit-hep/root_pandas#3]
Pandas features `HDFStore`, a class for easily inspecting and modifying HDF5 files.
Implementing a similar `ROOTStore` could alleviate some of the pain points that remain when working with root_pandas.

Examples where a `ROOTStore` could speed up working with ROOT files:
- Which trees are in this file?
- How many rows/columns do they contain?
- Saving several trees at once
- Adding a tree to an existing file
- Deleting a tree

**Comment by eduardo-rodrigues** [comment]
@chrisburr, I would simply close this task at this point.

**Comment by eduardo-rodrigues** [comment]
Nobody will work on this at this stage. Closing.
