### ISSUE TITLE
different TTree name for different file

### ISSUE THREAD

**Issue by wiso** [scikit-hep/root_pandas#37]
I have got different ROOT files. In each one I have a TTree (actually I have two TTrees per file, but I need only one). The names of the TTree are not the same for every ROOT file (actually it is equal to the name of the ROOT file).

Is it possible to have an interface like:

    read_root({'file1.root': 'tree1', 'file2.root': 'tree2', ...})

or

    read_root(({'path': 'file1.root', 'key':'tree1'},
               {'path': 'file2.root', 'key':'tree2'}))

**Comment by eduardo-rodrigues** [comment]
@wiso, as you may be aware, this package has been superseded by `https://github.com/scikit-hep/uproot`. I'm closing this task as "won't do" given what uproot provides. Hope that's OK. Feel free to ask any doubt you may have in `uproot` ...
