### ISSUE TITLE
write strings

### ISSUE THREAD

**Issue by wiso** [scikit-hep/root_pandas#43]
I guess this is connected with #38 but I am using a quite newer version of pandas (0.20.3)

    df = pandas.DataFrame({"x": [10, 20, 30], "y": ['ten', 'twenty', 'thirty']})
    print df.dtypes

    # x     int64
    # y    object
    # dtype: object

    df.to_root('t.root')
    f = ROOT.TFile.Open("t.root")   
    f.Get("default").Scan()       

    # ************************************
    # *    Row   *         x * __index__ *
    # ************************************
    # *        0 *        10 *         0 *
    # *        1 *        20 *         1 *
    # *        2 *        30 *         2 *
    # ************************************

why the string column is not written?

**Comment by MaxNoe** [comment]
Probably an issue for http://github.com/ibab/root_pandas

**Comment by eduardo-rodrigues** [comment]
As explicitly written in the README since a while, root_pandas, and root_numpy on which it depends, has been deprecated and effectively unmaintained for quite a while. We decided to close anthing outstanding as "won't do" and archive the package at this point.
