### ISSUE TITLE
Saving to a ROOT file with "/" in tree name

### ISSUE THREAD

**Issue by graipher** [scikit-hep/root_pandas#45]
In normal ROOT, trees may be within a `TDirectory`. This is transparent during reading (e.g., one can do `f->Get("DirectoryName/TreeName"` in C++).

However, when saving a `DataFrame` one cannot generate this directory structure. When saving a `DataFrame` with `key="DirectoryName/TreeName"`, this will just become the name of the tree. This object cannot be read back, because `f->Get("DirectoryName/TreeName"` will look for a tree with the name `TreeName` within the `TDirectory` `DirectoryName`, instead of a tree with that full name.

**Comment by graipher** [comment]
This is similar to a (closed) issue with `TDataFrame`, which I reported two years ago here: https://root-forum.cern.ch/t/tdirectory-in-tdataframe-snapshot/25134

**Comment by chrisburr** [comment]
Thanks for the report @graipher!

The `key` option in `root_pandas.to_root` is [passed directly to `root_numpy`](https://github.com/scikit-hep/root_pandas/blob/master/root_pandas/readwrite.py#L287) so your pull request there should fix it. We can then add a warning (or error) in `root_pandas` to check if someone tries to create a directory with a buggy version of `root_numpy`.

**Comment by graipher** [comment]
@chrisburr Yes, I noticed that afterwards as well (which is why I started creating a PR there). The warning sounds like a good idea.
