### ISSUE TITLE
Install root_pandas with miniconda on CERN lxplus: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by fdesse** [scikit-hep/root_pandas#51]
Hello everyone,
I hope I am asking this in the correct place.
I am trying to setup an environment using miniconda (conda 4.3.30)  on CERN's lxplus to work with root_pandas.

This is what I do:
`$ conda create --name=test-plain-pandas`
`$ source activate test-plain-pandas`
`$ conda install root_pandas`
`$ conda activate test`

The installation goes fine. The list of packages installed is the following:
![conda_list](https://user-images.githubusercontent.com/26150135/33133485-366fb30a-cf9d-11e7-8e95-a53b1e15ee9d.png)

 However, once the installation is done, if I try to run root:

`(test-plain-pandas) [fadesse@lxplus069 ewp-Bd2Kstee-AngAna]$ root -b -q `

I get the following error:

`root: /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/./libicui18n.so.58)`
`root: /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/./libicui18n.so.58)`
`root: /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/./libicuuc.so.58)`
`root: /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by /afs/cern.ch/work/f/fadesse/miniconda3/envs/test-plain-pandas/bin/../lib/./libicuuc.so.58)`

Any idea what I am doing wrong ?

Thank you for you help !

**Comment by fdesse** [comment]
Thank you very much for your reply. Indeed, installing with pip instead worked ! :)
Sorry for the noise, I guess I can close this issue. Hope this will be helpful to other people having the same problem.

**Comment by fdesse** [comment]
I'm sorry to reopen this issue. Your solution seemed to work, but now matplotlib is not working any more :(
If I do:
`from matplotlib import pyplot`
`ImportError: /afs/cern.ch/work/f/fadesse/miniconda3/envs/angAna/lib/./libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /afs/cern.ch/work/f/fadesse/miniconda3/envs/angAna/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-x86_64-linux-gnu.so)
`

It seems to me that this issue starts after installing root via
`conda install root`

Any idea what could make this happen ? Thx !

**Comment by fdesse** [comment]
I'm sorry to reopen this issue. Your solution seemed to work, but now matplotlib is not working any more :(
If I do:
`from matplotlib import pyplot`
`ImportError: /afs/cern.ch/work/f/fadesse/miniconda3/envs/angAna/lib/./libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by /afs/cern.ch/work/f/fadesse/miniconda3/envs/angAna/lib/python3.6/site-packages/matplotlib/_path.cpython-36m-x86_64-linux-gnu.so)
`

It seems to me that this issue starts after installing root via
`conda install root`

Any idea what could make this happen ? Thx !

**Comment by chrisburr** [comment]
It would be better to report this issue to the NLeSC repository so they can actually fix it.

I think this is caused by NLeSC shipping packages which are incompatible with Anaconda 5 (as it is now based on gcc 7.2). This hack fixes it for me:

```bash
cd $CONDA_PREFIX/lib
rm libstdc++.so.6
ln -s libstdc++.so.6.0.24 libstdc++.so.6
```

If the file `libstdc++.so.6.0.24` doesn't already exist, try `conda install gxx_linux-64`.

**Comment by chrisburr** [comment]
Thanks for making an issue upstream! 👍

(NLeSC/root-conda-recipes#32)
