### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by malbergo** [scikit-hep/root_pandas#56]
Hi there. I'm just trying to install this package but am not exactly sure how... I have python 2.7 (or python 3.5) and ROOT 5.34.36. Am I supposed to run setup.py with some certain options?

Thanks,
Michael

**Comment by chrisburr** [comment]
Hi @malbergo, `root_pandas` is available on pypi and can be installed using `pip`. The simplest form being:
```bash
pip install root_pandas
```
You may however need to modify this, depending on what operating system you use, how python is installed, how ROOT is installed and if you have root/admin privileges. My best guess for a command which will work for you would be:
```bash
python -m pip install --user root_pandas
```
or possibly:
```bash
python -m pip install --user --no-binary root_numpy root_pandas
```
