### ISSUE TITLE
Problem installing root_pandas with anaconda

### ISSUE THREAD

**Issue by renaudin** [scikit-hep/root_pandas#58]
Hi everyone,
I'm trying to set up a conda environment with ROOT and root_pandas installed using the latest miniconda on my laptop.
I didthe installation of ROOT in a fresh environment with success but when I'm trying to install root_pandas using `pip install root_pandas --no-binary root_numpy`, I have the following error:

![selection_038](https://user-images.githubusercontent.com/11870574/35945308-0f9f966e-0c60-11e8-8e1a-b214636338f4.png)

Did you already encounter such problem? Or does one of you have a workable setup of latest anaconda with root_pandas ?

Thank you very much for your help !

**Comment by eduardo-rodrigues** [comment]
Hi, I have not encountered this problem. But it is certainly a strange one since your compiler is not finding basic things such as libm and libc :S. I would try and debug in that direction, meaning, where are these libraries in your setup ...

**Comment by chrisburr** [comment]
How are you installing root? Can you give a full list of the commands used to create the environment?

**Comment by renaudin** [comment]
Thank you for spotting missing libraries, I will look at it.
I tried two things for installing ROOT, `conda install -c chrisburr root` and also installing it from NLesC, with the same result.

I also tried to install missing libraries with `conda install gxx_linux-64` but I was then unable to find the packages installed in my env, only the root ones were found.

**Comment by renaudin** [comment]
So, using `conda install gxx_linux-64`, I was able to install both root_numpy and root_pandas but when I try to import root_numpy (or root_pandas), I have the following error:

![selection_039](https://user-images.githubusercontent.com/11870574/35982039-13a55746-0cef-11e8-87b1-489c4f3b3056.png)
Do you have any hint ?
Thanks in advance,

**Comment by chrisburr** [comment]
Are you using `pip install --no-binary root_numpy ....` still?

 - If not the problem is probably that `root_numpy` was compiled with a different ROOT version to the one you have installed
 - If you did then you're picking up the ROOT libraries from the wrong place so you probably need to play with `LD_LIBRARY_PATH`

**Comment by renaudin** [comment]
Yes I am.
I'm trying to install root only after installing gxx_linux-64, hoping it will use this compiler.

**Comment by chrisburr** [comment]
What does `which gcc` and `gcc --version` give you?

**Comment by renaudin** [comment]
It gives me:
/home/renaudin/miniconda3/envs/cern/bin/gcc
gcc (GCC) 4.8.3 20140120 (prerelease)

My guess is that gcc and the conda cross-platform compiler are in conflict and the first one is picked for root then packages are compiled with the second.

**Comment by renaudin** [comment]
I also tried to install your root without depencies, in hope that only x86_64-conda_cos6-linux-gnu-c++ will be used, but I'm stuck with the same error.
And if I don't install gxx_linux-64, I have a compiler error during the root_numpy installation.

**Comment by renaudin** [comment]
Just to close the issue, I was able to install root_pandas getting back to Anaconda3-4.4.0.
I would be extremely interested if someone is able to make it work with latest anaconda but for the time being, this is all I need.
Many thanks for your help !

**Comment by chrisburr** [comment]
Thanks for reporting back. A few months ago (`v5`?) conda made major changes to the way gcc is used. It should be much better, but I'm not aware of anyone who has made an updated ROOT package yet. If anyone would like to I'd be happy to share my ideas for making it in a more maintainable way.
