### ISSUE TITLE
Cannot install root_pandas on Google colab

### ISSUE THREAD

**Issue by RemKamal** [scikit-hep/root_pandas#84]
Dear all,
after running the cell below, I get the following output:
!pip install --user root_pandas

Collecting root_pandas
  Using cached https://files.pythonhosted.org/packages/d4/5e/9f2d6e1c904bf0015e1fdf6718de88f8554083fdd8e112f3abad980351c6/root_pandas-0.7.0.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from root_pandas) (1.16.4)
Requirement already satisfied: pandas>=0.18.0 in /usr/local/lib/python3.6/dist-packages (from root_pandas) (0.24.2)
Collecting root_numpy (from root_pandas)
  Using cached https://files.pythonhosted.org/packages/d5/5f/82f5111c22599676eb8b5f9b1bf85c38dcc7995d52cd6b4a8f5f5caa4659/root_numpy-4.8.0.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Neither root_numpy or root_pandas get installed, all other libraries seem to work fine.

Thanks,
remkamal

**Comment by chrisburr** [comment]
Do you have a working installation of ROOT? (try `import ROOT`)

I don't know anything about Google colab but if you don't have ROOT and can use conda to install packages, that will be the easiest option: https://iscinumpy.gitlab.io/post/root-conda/

Alternatively, you could use `uproot` which is a pure Python package for reading ROOT files.

**Comment by RemKamal** [comment]
Hi Chris,
I guess this is the case, turned out I do not have ROOT, and the installation method at that link does not work as-is, I am trying other methods. 

Thanks.

**Comment by chrisburr** [comment]
Great, in that case I'll close this. If you have more questions feel free to keep commenting and if you find a good solution it might be useful to post it here so others can find it.
