### ISSUE TITLE
Segmentation fault with ROOT 6.22/02

### ISSUE THREAD

**Issue by donalrinho** [scikit-hep/root_pandas#89]
Dear all,

I am trying to use `root_pandas` to load a ROOT file into a data frame. The read fails like follows:

```
df = read_root("file.root", "DecayTree")
 *** Break *** segmentation violation
 *** Break *** segmentation violation
```

I am using conda forge to do a python env install like this:

```
wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $HOME/miniconda
source $HOME/miniconda/etc/profile.d/conda.sh
conda create -n ana_env python=3.7 root -c conda-forge
conda activate ana_env
conda config --env --add channels conda-forge
```
which gives me access to ROOT 6.22/02. The same ROOT files have been readable with `root_pandas` in previous conda installs I have done with the same setup options. The new conda install I have done today, which picks up ROOT 6.22/02, is the first time I have seen this error. I think 6.22/02 was released in August, so it's likely that this new ROOT version is causing the issue. 

Any help to resolve this would be super.

Many thanks,
Donal

**Comment by chrisburr** [comment]
Thanks for reporting, this should be fixed in an hour or so by https://github.com/conda-forge/root_numpy-feedstock/pull/16
