### ISSUE TITLE
Installing with pip 21.0.1 does not work, as pip tries to use wheel but doesn't fall back on setup.py install

### ISSUE THREAD

**Issue by donalrinho** [scikit-hep/root_pandas#90]
Hi there,

We are trying to install root_pandas using a new version of pip (21.0.1), which we got by doing:

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```
We see install errors for root_pandas, because pip tries to use wheel for the install which fails. With the new pip, pip does not fall back on `setup.py install`, and so the root_pandas install fails. Can wheel support for root_pandas be added?

Cheers!
Donal

**Comment by donalrinho** [comment]
Sorry, I think this has been caused by other errors in our setup steps. I see the following with root_pandas now:

```
Collecting root_pandas
  Using cached root_pandas-0.7.0-py3-none-any.whl
```
so it does seem to access a wheel.

**Comment by donalrinho** [comment]
However, when another user runs the same setup options, they see:

```
Collecting root_pandas
  Using cached root_pandas-0.7.0.tar.gz (9.7 kB)
  ```
 Is there a reason why pip is fetching the wheel for some users and the tar for another? Should we be asking pip to install `root-pandas` rather than `root_pandas`?

**Comment by eduardo-rodrigues** [comment]
Hi @donalrinho, no wheels are available in PyPI, see https://pypi.org/project/root-pandas/0.7.0/#files, so the wheels above are something you are building somehow? I don't know if @chrisburr has much more of an expert comment.

Aside this, you probably know that `root_pandas` is deprecated and hardly mantained these days, and we (within Scikit-HEP) divert everyone to use the `uproot` and `awkwards` series. Is there any reason why you still need this package? If there are then I would really urge you to post your needs so that in the end everyone profits from the extra functionality and we have a win-win :-).

**Comment by chrisburr** [comment]
> `root-pandas` rather `than root_pandas`

Pip treats underscores and dashes as identical in almost all contexts.

> so it does seem to access a wheel.

The difference between the messages is probably just that one of you has installed `root_pandas` before so `pip` has cached the wheel somewhere (`~/.cache`?).

Using `pip` 21 works fine for me locally (below) so I suspect you've missed the real error message in the log. My best guess would be that it's a problem with `root_numpy`, but any issues there are unlikely to be fixed as nobody has been maintaining it for years other than the occasional fixes I make to keep the conda-forge package alive (this is the main reason that `root_pandas` is deprecated). Can you share the entire output of running `pip install root_pandas`?

```bash
$ pip --version
pip 21.0.1 from /home/cburr/miniconda3/envs/test/lib/python3.9/site-packages/pip (python 3.9)
$ pip install root_pandas
Collecting root_pandas
  Downloading root_pandas-0.7.0.tar.gz (9.7 kB)
Requirement already satisfied: numpy in ./miniconda3/envs/test/lib/python3.9/site-packages (from root_pandas) (1.20.1)
Collecting pandas>=0.18.0
  Downloading pandas-1.2.2-cp39-cp39-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 5.4 MB/s
Requirement already satisfied: root_numpy in ./miniconda3/envs/test/lib/python3.9/site-packages (from root_pandas) (4.8.0)
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 102.0 MB/s
Requirement already satisfied: python-dateutil>=2.7.3 in ./miniconda3/envs/test/lib/python3.9/site-packages (from pandas>=0.18.0->root_pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/test/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=0.18.0->root_pandas) (1.15.0)
Building wheels for collected packages: root-pandas
  Building wheel for root-pandas (setup.py) ... done
  Created wheel for root-pandas: filename=root_pandas-0.7.0-py3-none-any.whl size=8805 sha256=ad2b066e059c05074fad9217d7ee28687efe4a542e1f75c7577ebdf15ddb1f61
  Stored in directory: /home/cburr/.cache/pip/wheels/68/da/c5/f1b413d49e9c9488d4b00c5bf87f86f4d942c3311a3e641f5d
Successfully built root-pandas
Installing collected packages: pytz, pandas, root-pandas
Successfully installed pandas-1.2.2 pytz-2021.1 root-pandas-0.7.0
```

**Comment by eduardo-rodrigues** [comment]
I think we can close this but please reopen @donalrinho if there is a need to.

**Comment by donalhill** [comment]
Hi all,

Yes indeed, please do close this. Sorry for not responding on the thread to both of you. We've moved to using `uproot` and `awkward` for handling, which is the best strategy longer-term. 

Cheers,
Donal

**Comment by eduardo-rodrigues** [comment]
Indeed. And, if you see functionality missing there, for your needs, then great if you can contribute ... :-)
