### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by shahidzk1** [scikit-hep/root_pandas#91]
Is parallel processing possible in root_pandas? If yes then how can I do it?

**Comment by chrisburr** [comment]
This somewhat depends on what exactly you mean by parallel processing however `root_pandas` has been unmaintained in quite a long time so you'll probably be better served by another tool. I've copied the deprecation notice from `root_numpy` (which underpins `root_pandas`) and contains the most popular alternatives, both of which can be used with pandas dataframes: https://github.com/scikit-hep/root_pandas#warningroot_pandas-is-deprecated-and-unmaintainedwarning

**Comment by eduardo-rodrigues** [comment]
As explicitly written in the README since a while, root_pandas, and root_numpy on which it depends, has been deprecated and effectively unmaintained for quite a while. We decided to close anthing outstanding as "won't do" and archive the package at this point.
